
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - .:/var/www
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: sdrimsacbot
      DB_USERNAME: sdrimsac
      DB_PASSWORD: "Sdrimsac@2025!"
      REDIS_HOST: redis
    depends_on:
      - mysql
      - redis
    networks:
      - appnet

  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: laravel_node
    working_dir: /var/www
    command: sh -c "npm install && npm run dev"
    volumes:
      - .:/var/www
      - node_modules:/var/www/node_modules
    ports:
      - "5173:5173"
    networks:
      - appnet
    depends_on:
      - app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sdrimsacbot
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sdrimsac
      MYSQL_PASSWORD: "Sdrimsac@2025!"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - appnet

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work --sleep=3 --tries=3 --timeout=90
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: sdrimsacbot
      DB_USERNAME: sdrimsac
      DB_PASSWORD: "Sdrimsac@2025!"
      REDIS_HOST: redis
    depends_on:
      - redis
      - mysql
    networks:
      - appnet

  whatsapp:
    build:
      context: ./modules/whatsapp
    container_name: whatsapp_node
    volumes:
      - ./modules/whatsapp/sessions:/app/sessions
    ports:
      - "3001:3001"
    networks:
      - appnet

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI
    networks:
      - appnet

networks:
  appnet:

volumes:
  mysql_data:
  node_modules:
