
services:
  app:
    build: .
    container_name: laravel_app
    env_file:
      - .env
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - appnet

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - appnet

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: sdrimsacbot
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: sdrimsac
      MYSQL_PASSWORD: "Sdrimsac@2025!"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - appnet

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - appnet

  queue:
    build: .
    command: php artisan queue:work --sleep=3 --tries=3
    env_file:
      - .env
    volumes:
      - .:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - appnet

networks:
  appnet:

volumes:
  mysql_data:
