server {
    listen 80;
    index index.php index.html;
    root /var/www/public;

    server_name _; # Puedes reemplazarlo con tu dominio si quieres

    # Página principal
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass laravel_app:9000;  # Nombre del servicio app + puerto PHP-FPM
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Proteger archivos .ht*
    location ~ /\.ht {
        deny all;
    }

    # Opcional: cache de assets
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires max;
        log_not_found off;
    }
}

